# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Security
  displayName: Security
  jobs:  
  - job: Security
    displayName: Security
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: 'horuszup/horusec-cli'
    steps:
    - script: sh /usr/local/bin/hoursec-cli.sh -p="./"
      displayName: 'Horusec Security'
